import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/components/client/NarBar'
import AuthUserContextProvider from '@/contexts/useAuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserContextProvider>
          <Nav />
          <main style={{paddingTop:70}}>
            {children}
          </main>
        </AuthUserContextProvider>
      </body>
    </html>
  )
}
